### ISSUE TITLE
Add a doc build step and preferably host these on a github.io site.

### ISSUE THREAD

**Issue by JacobHin2** [ziglibs/ansi-term#13]
I understand the docs generation is not stable yet etc... however it would be nice to have an easy way to read documentation w/o having to read the source for it.

You'll have to google to work out how you can add it as a step in build.zig
I would open a PR but its easier to ask first imo.

[Ziglearn docs for this.](https://ziglearn.org/chapter-3/#generating-documentation)

**Comment by joachimschmidt557** [comment]
Hi! I haven't set up automatic docs generation yet as the automated generation of documentation from source files is still a work-in-progress and I didn't want to make the impression that the generated docs are a stable feature of the Zig compiler. Other more popular zig libraries have also not opted for automatic docs generation because of this reason.

However, if you want to open a PR for automatic docs generation where the docs are linked with an explicit notice that the generated docs are a work-in-progress feature of the Zig compiler, I would gladly accept it!

**Comment by abhinav** [comment]
Hey, I've created https://github.com/ziglibs/ansi-term/pull/20 setting this up.
There's a preview at https://abhinav.github.io/ansi-term/.
The PR needs #19 to land first, though because ansi-term doesn't currently compile against the latest Zig nightly.
